### ISSUE TITLE
a.js引用a.jpg，脚本里面的的路径没有被替换成带MD5值的路径

### ISSUE THREAD

**Issue by FrendEr** [fouber/static-resource-digest#4]
dist/
├── map.json
└── public
    ├── a_c0c3f1f.jpg
    ├── a_e6a284b.js
    └── index.html

以上是执行了`rsd release -md ./dist`命令后的输出目录，可以看到a.jpg已经被重新命名为a_c0c3f1f.jpg输出了，但是。。。。

```
// a_e6a284b.js
var img = "a.jpg";
```

a.js被重新命名为a_e6a284b.js输出，但是里面的图片链接没被替换呢。

**Comment by fouber** [comment]
工具不会 `见到字符串就替换` ，所以，要想让工具识别资源定位标识，在js中要这样写：

``` js
var img = __uri("a.jpg");
```

**Comment by FrendEr** [comment]
谢谢，OK了！因为一开始试了html是可以的，所以没有考虑js会是另外的情况。这样的话，我们就不能定义像_uri这样的函数了，多少还是有点制约，不过目前看来还好。另外问下，_uri这样的api是fis提供的吗？看代码比较简单，还是依赖于fis模块的。

**Comment by fouber** [comment]
@FrendEr 是fis提供的功能
